changelog:
  exclude:
    labels:
      - chore
      - test 
      
  categories:
  - title: Breaking Changes 🛠
    labels:
    - breaking-change
  - title: Features 🎉
    labels:
    - feature
    - enhancement
  - title: Bug Fixes :bug:
    labels:
    - bug
  - title: Other Changes ;heavy_check_mark:
    labels:
       - documentation
       - refactor
       - "*"
